/* 
// 从highlight获得的所有支持语言

import h from "highlight.js";
const languagesList = h.listLanguages();
const langAliasMapping = languagesList
  .flatMap((each, index): [string, number][] | undefined =>
    h.getLanguage(each)?.aliases?.map((alias) => [alias, index])
  )
  .filter((each) => each != undefined); 
*/

/* prettier-ignore */
export const languagesList:ReadonlyArray<string> = 
  ["1c","abnf","accesslog","actionscript","ada","angelscript","apache",
  "applescript","arcade","arduino","armasm","xml","asciidoc","aspectj","autohotkey","autoit",
  "avrasm","awk","axapta","bash","basic","bnf","brainfuck","c","cal","capnproto","ceylon","clean",
  "clojure","clojure-repl","cmake","coffeescript","coq","cos","cpp","crmsh","crystal","csharp",
  "csp","css","d","markdown","dart","delphi","diff","django","dns","dockerfile","dos","dsconfig",
  "dts","dust","ebnf","elixir","elm","ruby","erb","erlang-repl","erlang","excel","fix","flix",
  "fortran","fsharp","gams","gauss","gcode","gherkin","glsl","gml","go","golo","gradle","graphql",
  "groovy","haml","handlebars","haskell","haxe","hsp","http","hy","inform7","ini","irpf90","isbl",
  "java","javascript","jboss-cli","json","julia","julia-repl","kotlin","lasso","latex","ldif",
  "leaf","less","lisp","livecodeserver","livescript","llvm","lsl","lua","makefile","mathematica",
  "matlab","maxima","mel","mercury","mipsasm","mizar","perl","mojolicious","monkey","moonscript",
  "n1ql","nestedtext","nginx","nim","nix","node-repl","nsis","objectivec","ocaml","openscad",
  "oxygene","parser3","pf","pgsql","php","php-template","plaintext","pony","powershell","processing",
  "profile","prolog","properties","protobuf","puppet","purebasic","python","python-repl","q","qml",
  "r","reasonml","rib","roboconf","routeros","rsl","ruleslanguage","rust","sas","scala","scheme",
  "scilab","scss","shell","smali","smalltalk","sml","sqf","sql","stan","stata","step21","stylus",
  "subunit","swift","taggerscript","yaml","tap","tcl","thrift","tp","twig","typescript","vala",
  "vbnet","vbscript","vbscript-html","verilog","vhdl","vim","wasm","wren","x86asm","xl","xquery",
  "zephir"];

export const langAliasAddition: ReadonlyArray<[string, number]> = [
  ["assembly", 188],
  ["asm", 188],
  ["rules", 152],
  ["tags", 171],
  ["vb.net", 180],
  ["livecode", 99],
  ["objective-c", 123],
  ["jboscli", 88],
];
export const langAliasMap: ReadonlyMap<string, number> = new Map([
  ["as", 3],
  ["asc", 5],
  ["apacheconf", 6],
  ["osascript", 7],
  ["ino", 9],
  ["arm", 10],
  ["html", 11],
  ["xhtml", 11],
  ["rss", 11],
  ["atom", 11],
  ["xjb", 11],
  ["xsd", 11],
  ["xsl", 11],
  ["plist", 11],
  ["wsf", 11],
  ["svg", 11],
  ["adoc", 12],
  ["ahk", 14],
  ["x++", 18],
  ["sh", 19],
  ["zsh", 19],
  ["bf", 22],
  ["h", 23],
  ["capnp", 25],
  ["icl", 27],
  ["dcl", 27],
  ["clj", 28],
  ["edn", 28],
  ["cmake.in", 30],
  ["coffee", 31],
  ["cson", 31],
  ["iced", 31],
  ["cls", 33],
  ["cc", 34],
  ["c++", 34],
  ["h++", 34],
  ["hpp", 34],
  ["hh", 34],
  ["hxx", 34],
  ["cxx", 34],
  ["crm", 35],
  ["pcmk", 35],
  ["cr", 36],
  ["cs", 37],
  ["c#", 37],
  ["md", 41],
  ["mkdown", 41],
  ["mkd", 41],
  ["dpr", 43],
  ["dfm", 43],
  ["pas", 43],
  ["pascal", 43],
  ["patch", 44],
  ["jinja", 45],
  ["bind", 46],
  ["zone", 46],
  ["docker", 47],
  ["bat", 48],
  ["cmd", 48],
  ["dst", 51],
  ["ex", 53],
  ["exs", 53],
  ["rb", 55],
  ["gemspec", 55],
  ["podspec", 55],
  ["thor", 55],
  ["irb", 55],
  ["erl", 58],
  ["xlsx", 59],
  ["xls", 59],
  ["f90", 62],
  ["f95", 62],
  ["fs", 63],
  ["f#", 63],
  ["gms", 64],
  ["gss", 65],
  ["nc", 66],
  ["feature", 67],
  ["golang", 70],
  ["gql", 73],
  ["hbs", 76],
  ["html.hbs", 76],
  ["html.handlebars", 76],
  ["htmlbars", 76],
  ["hs", 77],
  ["hx", 78],
  ["https", 80],
  ["hylang", 81],
  ["i7", 82],
  ["toml", 83],
  ["jsp", 86],
  ["js", 87],
  ["jsx", 87],
  ["mjs", 87],
  ["cjs", 87],
  ["wildfly-cli", 88],
  ["jsonc", 89],
  ["jldoctest", 91],
  ["kt", 92],
  ["kts", 92],
  ["ls", 93],
  ["lassoscript", 93],
  ["tex", 94],
  ["ls", 100],
  ["mk", 104],
  ["mak", 104],
  ["make", 104],
  ["mma", 105],
  ["wl", 105],
  ["m", 109],
  ["moo", 109],
  ["mips", 110],
  ["pl", 112],
  ["pm", 112],
  ["moon", 115],
  ["nt", 117],
  ["nginxconf", 118],
  ["nixos", 120],
  ["mm", 123],
  ["objc", 123],
  ["obj-c", 123],
  ["obj-c++", 123],
  ["objective-c++", 123],
  ["ml", 124],
  ["scad", 125],
  ["pf.conf", 128],
  ["postgres", 129],
  ["postgresql", 129],
  ["text", 132],
  ["txt", 132],
  ["pwsh", 134],
  ["ps", 134],
  ["ps1", 134],
  ["pde", 135],
  ["proto", 139],
  ["pp", 140],
  ["pb", 141],
  ["pbi", 141],
  ["py", 142],
  ["gyp", 142],
  ["ipython", 142],
  ["pycon", 143],
  ["k", 144],
  ["kdb", 144],
  ["qt", 145],
  ["re", 147],
  ["graph", 149],
  ["instances", 149],
  ["mikrotik", 150],
  ["rs", 153],
  ["scm", 156],
  ["sci", 157],
  ["console", 159],
  ["shellsession", 159],
  ["st", 161],
  ["ml", 162],
  ["stanfuncs", 165],
  ["do", 166],
  ["ado", 166],
  ["p21", 167],
  ["step", 167],
  ["stp", 167],
  ["styl", 168],
  ["yml", 172],
  ["tk", 174],
  ["craftcms", 177],
  ["ts", 178],
  ["tsx", 178],
  ["mts", 178],
  ["cts", 178],
  ["vb", 180],
  ["vbs", 181],
  ["v", 183],
  ["sv", 183],
  ["svh", 183],
  ["tao", 189],
  ["xpath", 190],
  ["xq", 190],
  ["xqm", 190],
  ["zep", 191],
  ...languagesList.map((each, index) => [each, index] as const),
  ...langAliasAddition,
]);
